// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Newsopedia.Data.Models;

namespace Newsopedia.Data.Migrations.NewsopediaOld
{
    [DbContext(typeof(NewsopediaOldContext))]
    [Migration("20211219202950_test2")]
    partial class test2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Newsopedia.Data.Models.GetTopUsers", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JunctionUserId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("GetTopUsers");
                });

            modelBuilder.Entity("Newsopedia.Data.Models.NewsTable", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NewsDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewsImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NewsImageURL");

                    b.Property<string>("NewsTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewsUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NewsId")
                        .HasName("PK_DateUrls");

                    b.ToTable("NewsTable");
                });

            modelBuilder.Entity("Newsopedia.Data.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Email" }, "Email_uc")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Newsopedia.Data.Models.UserNewsTable", b =>
                {
                    b.Property<int>("UserNewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NewsId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserNewsId");

                    b.HasIndex("NewsId");

                    b.HasIndex("UserId");

                    b.ToTable("User_NewsTable");
                });

            modelBuilder.Entity("Newsopedia.Data.Models.UserNewsTable", b =>
                {
                    b.HasOne("Newsopedia.Data.Models.NewsTable", "News")
                        .WithMany("UserNewsTables")
                        .HasForeignKey("NewsId")
                        .HasConstraintName("FK_User_NewsTable_NewsTable")
                        .IsRequired();

                    b.HasOne("Newsopedia.Data.Models.User", "User")
                        .WithMany("UserNewsTables")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_User_NewsTable_User")
                        .IsRequired();

                    b.Navigation("News");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Newsopedia.Data.Models.NewsTable", b =>
                {
                    b.Navigation("UserNewsTables");
                });

            modelBuilder.Entity("Newsopedia.Data.Models.User", b =>
                {
                    b.Navigation("UserNewsTables");
                });
#pragma warning restore 612, 618
        }
    }
}
